export default {
    contact: 'Contact',
    history: 'History',
    all: 'All',
    types: 'Types',
    humans: 'Humans',
    languages: 'Languages',
    framework: 'Framework',
    databases: 'Data bases',
    middleware: 'Middleware',
    os: 'Operating Systems',
    description: 'Chercheur/(lead-)développeur créatif, flexible, curieux et passionné par les solutions de recherche et leurs mises en œuvre par du prototypage.',
    subobjective: 'Trouver un poste d’architecte/ingénieur en informatique dans le domaine des systèmes d’information.',
    profile: 'Profile',
    objective: 'Objective',
    skills: 'Skills',
    hobbies: 'Hobbies',
    experience: 'Experience',
    education: 'Education',
    cv: 'Curriculum Vitae',
    website: '{name}\'s website',
    cancel: 'Cancel',
    ok: 'Ok',
    test: 'Test',
    impaired: 'Impaired eyes',
    paired: 'Paired eyes',
    edit: 'Edit',
    create: 'Create',
    read: 'Read',
    update: 'Update',
    delete: 'Delete',
    deleteAll: 'Delete all',
    notadmin: 'You are not an administrator',
    admin: 'Administration',
    add: 'Add',
    search: 'Search {name}',
    dataViewer: 'Data viewer',
    systemMessage: 'System message',
    systemMessages: 'System messages',
    reset: 'Reset',
    grid: 'Grid',
    table: 'Table',
    network: 'Network',
    rememberMe: 'Remember me',
    stayLogged: 'Stay logged',
    alreadyLogged: 'Already logged such as {pseudo}',
    go: 'Go',
    push: 'Push',
    replace: 'Replace',
    block: 'Block',
    404: '404: this page does not exist',
    settings: 'Settings',
    process: 'Process',
    processes: 'Processes',
    redirection: 'Redirection',
    home: 'Home',
    error: 'Error',
    errors: 'Errors',
    state: 'State',
    states: 'States',
    renewId: 'Renew Identifier',
    close: 'Close',
    id: 'Id',
    payload: 'Payload',
    response: 'Response',
    answer: 'Answer',
    processing: 'Processing',
    requests: 'Requests',
    details: 'Details',
    pages: 'Pages',
    about: 'About',
    contribute: 'Contribute',
    designer: 'Designer',
    FAQ: 'Frequently Asked Questions',
    faq: 'Frequently Asked Questions',
    help: 'Help',
    loading: 'Loading',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm password',
    usernameOrEmail: 'Username or EMail',
    email: 'EMail',
    new_account: 'New account ?',
    sendRenewId: 'Send renew password key',
    renewPassword: 'Renew password',
    validate: 'Validate',
    signin: 'Sign in',
    login: 'Log in',
    logout: 'Log out',
    welcome: 'Welcome',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    submit: 'Submit',
}
