export default {
    contact: 'Contact',
    history: 'Historique',
    all: 'Tout',
    types: 'Types',
    humans: 'Humain',
    languages: 'Langages',
    framework: 'Canevas',
    databases: 'Bases de données',
    middleware: 'Intergiciels',
    os: 'Systèmes d\'exploitation',
    description: 'Chercheur (7 ans)/lead-développeur (3 ans) créatif, flexible, curieux et passionné par les solutions de recherche et leurs mises en œuvre par du prototypage',
    subobjective: 'Trouver un poste d’architecte/ingénieur en informatique dans le domaine des systèmes d’information',
    profile: 'Profil',
    objective: 'Objectif',
    skills: 'Compétences',
    hobbies: 'Loisirs',
    experience: 'Expérience',
    education: 'Formation',
    cv: 'Curriculum Vitae',
    website: 'Site web de {name}',
    cancel: 'Annuler',
    ok: 'Valider',
    test: 'Test',
    impaired: 'Mal-voyant',
    paired: 'Voyant',
    edit: 'Edit',
    create: 'Créer',
    read: 'Lire',
    update: 'Mettre à jour',
    delete: 'Supprimer',
    deleteAll: 'Tout supprimer',
    notadmin: 'Vous n\'êtes pas un administrateur',
    admin: 'Administration',
    add: 'Ajouter',
    search: 'Recherche',
    dataViewer: 'Visualisation de données',
    systemMessage: 'Message du système',
    systemMessages: 'Messages du système',
    reset: 'Réinitialiser',
    grid: 'Grille',
    table: 'Tableau',
    network: 'Réseau',
    rememberMe: 'Se souvenir de moi',
    stayLogged: 'Rester connecté',
    alreadyLogged: 'Vous êtes déjà connecté en tant que {pseudo}',
    go: 'Aller',
    push: 'Pousser',
    replace: 'Remplacer',
    block: 'Bloquer',
    404: '404: cette page n\'existe pas',
    settings: 'Paramètres',
    redirection: 'Redirection',
    home: 'Accueil',
    error: 'Erreur',
    errors: 'Erreurs',
    state: 'État',
    states: 'États',
    renewId: 'Identifiant de renouvellement',
    close: 'Fermer',
    id: 'Id',
    message: 'Message',
    payload: 'Payload',
    response: 'Réponse',
    answer: 'Réponse',
    processing: 'Traitement',
    requests: 'Requêtes',
    details: 'Détails',
    pages: 'Pages',
    about: 'À propos',
    contribute: 'Contribuer',
    designer: 'Modeleur',
    FAQ: 'Foire aux questions',
    faq: 'Foire aux questions',
    help: 'Aide',
    loading: 'Chargement',
    username: 'Identifiant',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    usernameOrEmail: 'Identifiant ou EMail',
    email: 'EMail',
    newAccount: 'Nouveau compte ?',
    sendRenewId: 'Envoyer la clef de renouvellement de mot de passe',
    renewPassword: 'Réinitialiser le mot de passe',
    validate: 'Valider',
    signin: 'Inscription',
    login: 'Connexion',
    logout: 'Déconnexion',
    subtitle: 'Multi base de données sous ACID',
    welcome: 'Bienvenue',
    switchLanguage: 'Changer de langue',
    twitterMessage: 'Nous sommes sur Twitter',
    submit: 'Soumettre',
}
